package com.nsb.pojo;

import java.util.Date;

public class Process {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.mac
     *
     * @mbggenerated
     */
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.process
     *
     * @mbggenerated
     */
    private String process;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.id
     *
     * @return the value of process.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.id
     *
     * @param id the value for process.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.mac
     *
     * @return the value of process.mac
     *
     * @mbggenerated
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.mac
     *
     * @param mac the value for process.mac
     *
     * @mbggenerated
     */
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.process
     *
     * @return the value of process.process
     *
     * @mbggenerated
     */
    public String getProcess() {
        return process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.process
     *
     * @param process the value for process.process
     *
     * @mbggenerated
     */
    public void setProcess(String process) {
        this.process = process == null ? null : process.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.create_time
     *
     * @return the value of process.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.create_time
     *
     * @param createTime the value for process.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.update_time
     *
     * @return the value of process.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.update_time
     *
     * @param updateTime the value for process.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}