package com.nsb.dao;

import com.nsb.pojo.Information;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface InformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    int insert(Information record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    int insertSelective(Information record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    Information selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Information record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Information record);

    int checkMac(String mac);

    String selectMacByIp(String ip);

    int updateStatusByMac(@Param("mac") String mac, @Param("status") String status);

    List<Information> getComInfo(String roomId);

    List<Information> getCommandInfo(String roomId);

    int checkStatus(@Param("mac") String mac, @Param("status") String status);

    int checkRoomId(String roomId);

    int checkAll(String status);

    List<Information> getMacByStatus(String status);

    int checkStatusByRoomId(@Param("roomId") String roomId, @Param("status") String status);

    int updateRoomIdByMac(@Param("roomId") String roomId, @Param("mac") String mac);
}